### PR TITLE
WIP: Finagle Core -> 2.13

### PR DESCRIPTION
**Pull request by martijnhoekstra**
Problem

There is no 2.13 release for finagle core

Solution

Make a 2.13 build

Result

A 2.13 build

### CODE REVIEW

File: finagle-core/src/main/scala/com/twitter/finagle/Dtab.scala [hunk 1]
```diff
@@ -112,9 +103,9 @@ case class Dtab(dentries0: IndexedSeq[Dentry]) extends IndexedSeq[Dentry] {
    */
   def simplified: Dtab =
     Dtab({
-      val simple = this map {
+      val simple = self.map { entry => entry match {
```
Comment (martijnhoekstra) [inline finagle-core/src/main/scala/com/twitter/finagle/Dtab.scala]: Todo: figure out why this is needed

File: finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala [hunk 2]
```diff
@@ -130,9 +130,9 @@ final class MarshalledContext private[context] extends Context {
 
   // Exposed for testing
   private[context] def marshal(env: Map[Buf, Cell]): Iterable[(Buf, Buf)] = {
-    env.mapValues {
-      case Real(k, v) => k.marshal(v.x)
-      case Translucent(_, vBuf) => vBuf
+    env.transform {
```
Comment (martijnhoekstra) [inline finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala]: todo: What?

File: finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala [hunk 3]
```diff
@@ -227,7 +228,7 @@ class TrafficDistributorTest extends FunSuite {
       }.head
 
       result.foreach {
-        case ((w, _, l)) => assert(math.abs(l / w - baseline) <= baseline * ε)
+        case ((w, _, l)) => assert(math.abs(l / w - baseline) <= baseline * ε, "second one")
```
Comment (martijnhoekstra) [inline finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala]: This test is failing, todo: figure out why (and fix it)

**Comment by martijnhoekstra** [comment]
blocked by https://github.com/twitter/scrooge/pull/314 and (directly and transitively) https://github.com/twitter/util/issues/253

**Comment by martijnhoekstra** [comment]
Todo: rebase (redo?) on top of https://github.com/twitter/finagle/pull/789

File: finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala (hunk 3 above)
Comment (martijnhoekstra) [reply finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala]: Increasing the size for R makes the test pass. I'm not sure if there is an underlying problem here, or that it was just unlucky RNG from the given seed.

File: finagle-base-http/src/main/scala/com/twitter/finagle/http/ProxyCredentials.scala [hunk 4]
```diff
@@ -2,13 +2,13 @@ package com.twitter.finagle.http
...
-import scala.collection.JavaConversions._
+import scala.collection.JavaConverters._
 
 object ProxyCredentials {
   def apply(credentials: java.util.Map[String, String]): Option[ProxyCredentials] =
-    apply(credentials.toMap)
+    apply(credentials.asScala)
 
-  def apply(credentials: Map[String, String]): Option[ProxyCredentials] = {
+  def apply(credentials: scala.collection.Map[String, String]): Option[ProxyCredentials] = {
```
Comment (mosesn) [inline finagle-base-http/src/main/scala/com/twitter/finagle/http/ProxyCredentials.scala]: as I mentioned on the other review, let's keep this one immutable.Map

File: finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+ * @see The [[https://twitter.github.io/finagle/guide/Names.html#interpreting-paths-with-delegation-tables user guide]]
+ *      for further details.
+ */
+case class Dtab(dentries0: IndexedSeq[Dentry]) extends DtabBase
+
+object Dtab extends DtabCompanionBase {
+  
+}
+
+final class DtabBuilder extends ReusableBuilder[Dentry, Dtab] {
```
Comment (mosesn) [inline finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala]: can we document the distinction between the 2.12 stuff vs the 2.13 stuff?  would we be able to just use this if we didn't need to build for 2.11, for example?

File: finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala [hunk 6]
```diff
@@ -0,0 +1,13 @@
+package com.twitter.finagle
+
+/**
+ * Static methods for Java callers
```
Comment (mosesn) [inline finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: I love that you're thinking of java users here!  But shouldn't java-users be able to use static forwarders on Dtab?  If they can't, why can't they?

File: finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala [hunk 7]
```diff
@@ -0,0 +1,13 @@
+package com.twitter.finagle
+
+/**
+ * Static methods for Java callers
+ */
+object Dtabs {
+  def empty() = Dtab(Vector.empty[Dentry])
```
Comment (mosesn) [inline finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: type annotations please!

File: finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala (hunk 2 above)
Comment (mosesn) [reply finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala]: this is a bummer.  should we keep it mapValues and suppress deprecations?  or add some kind of TODO to change it back after the new mapValues is rolled out?

File: finagle-core/src/test/scala/com/twitter/finagle/util/CachedHashCodeTest.scala [hunk 8]
```diff
@@ -48,8 +48,12 @@ class CachedHashCodeTest extends FunSuite {
   }
 
   test("same hashCode mixed in or not") {
-    case class NotMixedIn(s: String)
-    case class MixedIn(s: String) extends CachedHashCode.ForCaseClass
+    case class NotMixedIn(s: String) {
+      override def productPrefix = "prefix"
```
Comment (mosesn) [inline finagle-core/src/test/scala/com/twitter/finagle/util/CachedHashCodeTest.scala]: why do we have to do this?  can you add a comment?

File: finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala (hunk 5 above)
Comment (martijnhoekstra) [reply finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala]: The 2.12 version has `CanBuildFrom`, and 2.13 doesn't. Without it you will never be able to map a `Dtab` with a `Dentry => Int` and get back a `BitSet`.

It's a bit of a niche concern I suppose. You could consider breaking downstream and just have a Dentry => Dentry overload of map, and if 2.13 was all we ever knew and this was greenfields, it would probably be a good idea.  Whether it's enough of a justification to break downstream if they are doing something I consider moderately silly is really not up to me.

File: finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala (hunk 2 above)
Comment (martijnhoekstra) [reply finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala]: `transform` is AFAIK the fastest of the current options. I have no strong opinions on the matter, other than that unrelatedly the first case should maybe have been `case (_, Real(k, Some(v)) => k.marshal(v)`

File: finagle-base-http/src/main/scala/com/twitter/finagle/http/ProxyCredentials.scala (hunk 4 above)
Comment (martijnhoekstra) [reply finagle-base-http/src/main/scala/com/twitter/finagle/http/ProxyCredentials.scala]: This commit is also in the other one -- I'll rebase again once it's in, and the change should come along with that.

File: finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala (hunk 6 above)
Comment (martijnhoekstra) [reply finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: The java compilation test started failing, so I just did what I had to do. I assumed that the underlying cause there are no static forwarders anymore is because we go through a common trait now, based on the flimsiest of intuition. I'll do some experiments to find the cause, and see what bytecode is generated under what conditions.

File: finagle-core/src/test/scala/com/twitter/finagle/util/CachedHashCodeTest.scala (hunk 8 above)
Comment (martijnhoekstra) [reply finagle-core/src/test/scala/com/twitter/finagle/util/CachedHashCodeTest.scala]: Added comment above:

    //case class productPrefix (class name) gets mixed in
    //into hash in 2.13+, so we have to override
    //it if we want to check whether to separate
    //case classes would have hashed the same if
    //the only difference had been the mixin.

File: finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala (hunk 2 above)
Comment (mosesn) [reply finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala]: yeah, that makes sense–but presumably mapValues will be cheaper than transform when it's reimplemented, since it won't be wrapping the kv pairs in tuples, so I'd like a reminder to switch back to mapValues when it exists (hence the TODO).

I'd be down to switch it, except that I don't know if the Some unapply gets desugared to allocate an Option?  my hunch is that case class unapply is special and avoids it, but idk.  as an aside, I was looking at the API, and it looks like we can use .value instead of .get if we know it's a `Some`, which `Real` already guarantees for us.  should we use .value?

File: finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala (hunk 6 above)
Comment (mosesn) [reply finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: I'd rather keep those static forwarders if we can.  might be worth duplicating more code, or else making DtabBase an abstract class.

File: finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala (hunk 2 above)
Comment (martijnhoekstra) [reply finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala]: case class unapply is indeed special and doesn't have to allocate anything. `value` was introduced in `2.12`, `get` is needed for 2.11 compat. `get` probably gets jitted to direct field access pretty quickly, so from a performance perspective it doesn't matter much. But if you're still pining for a reason to get rid of 2.11, this may be your ticket -- but again, I'm fine with whatever.

Comment (mosesn) [reply finagle-core/src/main/scala/com/twitter/finagle/context/MarshalledContext.scala]: if case class unapply is special, let's use it.  :shipit:

File: finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala (hunk 6 above)
Comment (martijnhoekstra) [reply finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: I'll toy with it a bit. I'll get them back one way or another.

Comment (martijnhoekstra) [reply finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: I thought I broke my local cache with that last one. I either broke scalac or sbt. Oh well.

Comment (mosesn) [reply finagle-core/src/main/scala/com/twitter/finagle/Dtabs.scala]: thanks!

**Comment by mosesn** [comment]
Now that your patch for fixing up the deprecations is merged in, can you rebase against develop when you get a chance?

**Comment by martijnhoekstra** [comment]
Yes, as soon as I find the time

**Comment by martijnhoekstra** [comment]
CI depends on finagle-memcached, which depends on bijection-core, which is on its way at https://github.com/twitter/bijection/pull/289

Not sure how easy memcached will be once the dependencies are met, but it seems out of scope for this PR

**Comment by mosesn** [comment]
Agreed.  Let's not add 2.13.x to travisci in this review, imo.

File: finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala (hunk 5 above)
Comment (mosesn) [reply finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala]: right.  I'm wondering if we can add a comment to this file that explains why we have to make this change?  it sounds like behavior is changing incompatibly when we switch to 2.13.x anyway, so maybe the TODO is to make the breaking change in <= 2.12.x to unify the builds and prepare users for 2.13.x?  we could add that as a comment too.

File: finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala [hunk 9]
```diff
@@ -68,8 +68,9 @@ private object TrafficDistributorTest {
     override def toString: String = s"Balancer($endpoints)"
   }
 
-  // Return the distribution for the the given `balancer` as a tuple
-  // of (weight, size, offer load).
+  /** Return the distribution for the the given `balancer` as a tuple
```
Comment (mosesn) [inline finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala]: can we start the sentence that begins with "Return" on the next line?  I think that's the scaladoc style we normally use.

File: finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala [hunk 10]
```diff
@@ -204,7 +205,7 @@ class TrafficDistributorTest extends FunSuite {
     }
 
     locally {
-      val R = 10 * 1000
+      val R = 100 * 1000
```
Comment (mosesn) [inline finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala]: it's really bizarre that you found it didn't work.  can we try doing it with 10K again?  I'd rather not change it if we don't have to.

File: finagle-toggle/src/main/scala/com/twitter/finagle/toggle/JsonToggleMap.scala [hunk 11]
```diff
@@ -126,13 +126,13 @@ object JsonToggleMap {
       }
 
       val metadata: immutable.Seq[Toggle.Metadata] =
-        toggles.map { jsonToggle =>
+        toggles.map(jsonToggle => {
```
Comment (mosesn) [inline finagle-toggle/src/main/scala/com/twitter/finagle/toggle/JsonToggleMap.scala]: why did we have to switch this to use curlies inside instead of outside?

File: finagle-toggle/src/main/scala/com/twitter/finagle/toggle/ToggleMap.scala [hunk 12]
```diff
@@ -351,9 +344,9 @@ object ToggleMap {
   class Immutable(metadata: immutable.Seq[Toggle.Metadata]) extends ToggleMap {
 
     private[this] val toggles: immutable.Map[String, Toggle[Int]] =
-      metadata.map { md =>
+      metadata.map(md =>
```
Comment (mosesn) [inline finagle-toggle/src/main/scala/com/twitter/finagle/toggle/ToggleMap.scala]: ditto, why can't this use curlies anymore?

File: finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala (hunk 10 above)
Comment (martijnhoekstra) [reply finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala]: I'll see if changing the seed does anything -- it's taken from a hash from a string, and there are some hash changes.

File: finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala (hunk 9 above)
Comment (martijnhoekstra) [reply finagle-core/src/test/scala/com/twitter/finagle/loadbalancer/TrafficDistributorTest.scala]: Will do

File: finagle-toggle/src/main/scala/com/twitter/finagle/toggle/JsonToggleMap.scala (hunk 11 above)
Comment (martijnhoekstra) [reply finagle-toggle/src/main/scala/com/twitter/finagle/toggle/JsonToggleMap.scala]: I could have sworn I had some deprecation warnings for this,  but I can't reproduce that anymore, so it can be changed back.

File: finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala (hunk 5 above)
Comment (martijnhoekstra) [reply finagle-core/src/main/scala-2.13+/com/twitter/finagle/Dtab.scala]: I'll try to make this a bit neater, and make some compilation and run tests to demonstrate what behaviour is unified (and document what is and isn't). For an integrated collection in 2.13 the companion should extend `Factory` (among other reasons?) so that `Iterable#to(Dtab)` works, and that should also work on 2.12 with the scala.collection.compat library.

**Comment by mosesn** [comment]
Sounds like a plan, thank you!

**Comment by martijnhoekstra** [comment]
I am a bit bogged down, I'll have some more time tomorrow, but don't hold off for that if you want to push it through.

**Comment by mosesn** [comment]
Weird, I ran into this error:

```
[error] /Users/mnakamura/workspace/sources/0/finagle/finagle-core/src/test/java/com/twitter/finagle/DtabCompilationTest.java:11:1: non-static method empty() cannot be referenced from a static context
[error]     Dtab d = Dtab.empty();
[error] /Users/mnakamura/workspace/sources/0/finagle/finagle-core/src/test/java/com/twitter/finagle/DtabCompilationTest.java:11:1: incompatible types: scala.collection.IterableOps cannot be converted to com.twitter.finagle.Dtab
[error]     Dtab d = Dtab.empty();
[error] /Users/mnakamura/workspace/sources/0/finagle/finagle-core/src/test/java/com/twitter/finagle/DtabCompilationTest.java:16:1: non-static method empty() cannot be referenced from a static context
[error]     Dtab.setBase(Dtab.empty());
[error] /Users/mnakamura/workspace/sources/0/finagle/finagle-core/src/test/java/com/twitter/finagle/DtabCompilationTest.java:16:1: incompatible types: scala.collection.IterableOps cannot be converted to com.twitter.finagle.Dtab
[error]     Dtab.setBase(Dtab.empty());
[error] /Users/mnakamura/workspace/sources/0/finagle/finagle-core/src/test/java/com/twitter/finagle/StackParamCompilationTest.java:80:1: non-static method empty() cannot be referenced from a static context
[error]               public Dtab apply() { return Dtab.empty(); }
[error] /Users/mnakamura/workspace/sources/0/finagle/finagle-core/src/test/java/com/twitter/finagle/StackParamCompilationTest.java:80:1: incompatible types: scala.collection.IterableOps cannot be converted to com.twitter.finagle.Dtab
[error]               public Dtab apply() { return Dtab.empty(); }
[info] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[error] (Test / compileIncremental) javac returned non-zero exit code
[error] Total time: 23 s, completed Aug 29, 2019 3:14:02 PM
```

**Comment by martijnhoekstra** [comment]
That's the same problem as the one I initially fixed by making the DTabs
object, and thought was also fixed with the abstract base classes instead
of the base traits.

**Comment by mosesn** [comment]
> That's the same problem as the one I initially fixed by making the DTabs object, and thought was also fixed with the abstract base classes instead of the base traits.
Hmm, doesn't seem to be fixed on my machine.  I think this might be a bug in scalac–when I javap, I see two methods named empty, and neither of them is static.

```
  public scala.collection.IterableOps empty();
  public java.lang.Object empty();
```

**Comment by mosesn** [comment]
ahhhhhh, it's because DtabBase extends IndexedSeq[Dentry] which has an `empty` method.  the empty methods collide.

**Comment by mosesn** [comment]
https://github.com/scala/scala/commit/a864ae04c48b9be94b00345668e8ecaf85fc24da
😠  ok, looks like we actually need to come up with a solution for this.

**Comment by martijnhoekstra** [comment]
Yikes. 

What are our options here, other than lament the state of affairs we're in?

* Do a static forwarder object: that's a breaking change
* Find a different name for `empty`: that's also a breaking change, though it breaks less. It's also inelegant. 
* Find out if we can convince scalac to emit a static override. Is that a thing in the JVM? It's not a thing in Java, probbaly for good reason. This seems like a *really* bad idea
* Other?

**Comment by mosesn** [comment]
I think I'm going to add a new name for java compat.  How does Dtab.emptyDtab sound to you?

**Comment by martijnhoekstra** [comment]
A bit verbose, but I don't think there are much better options. Another option might be `blank` -- a blank table is empty, semantically it fits nicely, but that is probably a lot less discoverable, particularly through auto-completion tools.

**Comment by mosesn** [comment]
the R = 100 * 1000 thing is bewildering. I think we're going to increase it for now, and reduce it again when we get a handle on what's going on.

**Comment by martijnhoekstra** [comment]
The R = n thing seems to be fully deterministic btw.

What I noticed before was that `val classes = weightClasses.flatMap(weightClass.tupled).toSet` iterates over its values in a different order in 2.12 and 2.13, so that something may have randomly changed is plausible. That it's a red herring maybe more plausible.

changing the seed to `"seed2"` in `newDist` fixes the problem for me.

**Comment by mosesn** [comment]
???? it sounds like this is just a bad test.  I tried changing the seed to "deadbeef" and that didn't work.

**Comment by martijnhoekstra** [comment]
I don't know what I'm seeing and not seeing anymore.

**Comment by mosesn** [comment]
I can reproduce that "seed2" fixes it.  This is wild.  We need to come back to this later and understand what's wrong with this test.

**Comment by martijnhoekstra** [comment]
"seed2" break the test on 2.12. The test is just too sensitive to "small" diviations I suppose.

**Comment by mosesn** [comment]
ugh, you're right.  I'll leave it as 100 * 1000 with "seed" for now.

**Comment by mosesn** [comment]
@martijnhoekstra we had some questions about why we're switching to VectorBuilder instead of ArrayBuffer or ListBuffer (since we've found in the past that Vectors can be pretty heavy in comparison).  What's your thinking there?

**Comment by martijnhoekstra** [comment]
As discussed on gitter -- the builders can build in O(1), but Vectors may not be suitable for anything. Getting a Builder for some collection is best done through `CC.newBuilder`, so a ListBuilder through List.newBuilder and an array backed seq through `ArraySeq.newBuilder`. This requires scala.collection.compat to make cross-compile.

**Comment by mosesn** [comment]
this ended up being way more trouble than I thought it would be . . . but it's in!!! merged in here: https://github.com/twitter/finagle/commit/f21a54e0d759e005e089e9996113548078044498

thanks so much @martijnhoekstra!

**Comment by martijnhoekstra** [comment]
Great! This should unblock all of finagle, and lots of other stuff as well.
