### ISSUE TITLE
set contentString is broken

### ISSUE THREAD

**Issue by rogern** [twitter/finagle#593]
Setting contentString on a Response fails with a ClassNotFoundException on Buf$Indexed

I'm using finagle-core_2.11-6.42.0 and can no longer set the contentString on a Response.
It fails here:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/twitter/io/Buf$Indexed
	at com.twitter.finagle.netty3.BufChannelBuffer$.apply(BufChannelBuffer.scala:92)
	at com.twitter.finagle.netty3.BufChannelBuffer$.apply(BufChannelBuffer.scala:106)
	at com.twitter.finagle.http.Message.contentString_$eq(Message.scala:342)
```
This simple code shows the bug:
```
package finaglebug

import com.twitter.finagle.http.Response

object Main {
  def main(args: Array[String]): Unit = {
    val r = Response()
    r.contentString = """{"json":"test"}"""
  }
}
```

This worked in finagle 6.32.0

**Comment by mosesn** [comment]
@rogern NoClassDefFound often indicates that there's a classpath mismatch.  Can you check that you only have one version of `util-core` on your classpath, and that it's the one that `finagle-http` 6.42.0 depends on?

**Comment by rogern** [comment]
@mosesn Oh, so I need to depend on util-core 6.41.0 when using finagle 6.42.0! I probably missed that in the doc somewhere =) Maybe not so obvious ;)
I tried to slim down my project as much as possible but still I had quite a few dependencies on util-core since Future class is part of it.
