### ISSUE TITLE
finagle-thrift does not work with libthrift-0.9.1 or greater

### ISSUE THREAD

**Issue by jluehe** [twitter/finagle#673]
finagle-thrift does not work with libthrift-0.9.1 or greater

### Expected behavior

finagle-thrift should work with latest libthrift version 

### Actual behavior

finagle-thrift depends on libthrift-0.5.0: https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/scala/BUILD#L10.
As such, it is able to call 3-argument constructor of org.apache.thrift.protocol.TBinaryProtocol$Factory: https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/scala/com/twitter/finagle/thrift/Protocols.scala#L70
This constructor was removed from libthrift-0.9.1 (and greater), causing this runtime error:

  Caused by: java.lang.NoSuchMethodError: org.apache.thrift.protocol.TBinaryProtocol$Factory.<init>(ZZI)V
    at com.twitter.finagle.thrift.Protocols$.binaryFactory(Protocols.scala:66)
    at com.twitter.finagle.Thrift$.<init>(Thrift.scala:151)
    at com.twitter.finagle.Thrift$.<clinit>(Thrift.scala)
    at com.twitter.finagle.Thrift.client(Thrift.scala)  

### Steps to reproduce the behavior

Link finagle-thrift against libthrift-0.9.1 (or greater) and run with Java 9

**Comment by yufangong** [comment]
@jluehe thank you for the report! We are working on upgrading our libthrift dependency to 0.10.0 now, however, we need to fully test it before merging. We will let you know when it happens.

**Comment by jluehe** [comment]
Sounds great, @yufangong - thanks for keeping me in the loop!

**Comment by smlance** [comment]
Closing this since we upgraded to libthrift-0.10.0 as of https://github.com/twitter/finagle/commit/61c7a71182866250e53f9731c46f31dde28d464c.

**Comment by cricket007** [comment]
@smlance @yufangong Is there a particular reason Thrift 0.11.0 wasn't used? Other than perhaps it wasn't released at the time you started the upgrades?

Also, I'm just starting to look at Finagle for an RPC Thrift use case (in Java and using Maven), and I finding it difficult to line up versions between Scrooge, Finagle-thrift, and libthrift. For example, the Scrooge web page says to add version `4.13.0`, but I see that's rather old. I assume all versions of these libraries should closely match? And I'll need to wait until the next release for Thrift 0.10.0 anyway?  

Thanks

**Comment by mosesn** [comment]
@cricket007 part of it was that it wasn't released when we started, but the bigger piece is that thrift 0.10.0 was stable for a long time, and we don't know what issues 0.11.0 will have.  we figured it made more sense to wait and see for a few months whether they rush to get a patched version before immediately moving to the latest and greatest.

If you go to maven central or the badge in the finagle README, you can see when libraries have been published most recently.  We've recently switched our versioning to be YY.month.0, so the most recently published version across both scrooge and finagle was 18.3.0, and the next one will be 18.4.0.  We don't control libthrift, so we can't synchronize that one.

Yep, you'll want to wait until 18.4.0 if you want to use libthrift 0.10.x.
