### PR TITLE
finagle-serversets: -> 2.13

### PR DESCRIPTION
**Pull request by joroKr21**
Problem

no 2.13 cross build

Solution
  * Use `scala.jdk.CollectionConverters` from collection-compat
  * Replace usages of `Unit` as a value with `()`
  * `EntryTest` - don't observe the order of keys in a map

Result

`finagle-serversets` compiles on 2.13 and tests are passing.

Ref #771

### CODE REVIEW

**Comment by joroKr21** [comment]
Uhm, how can we add Scala 2.13 to the Travis matrix only for some projects?

**Comment by mosesn** [comment]
> Uhm, how can we add Scala 2.13 to the Travis matrix only for some projects?

I don't think it's worth it to invest in it, we're going to be able to just turn on 2.13 in general anyway soon =)

**Comment by joroKr21** [comment]
Updated description :+1:

**Comment by mosesn** [comment]
@joroKr21 can you confirm how you tested it against 2.13?  It's failing when we try it.

```
[error] .../finagle/finagle-serversets/src/main/java/com/twitter/finagle/common/zookeeper/Group.java:47:8: value ZooKeeperConnectionException is not a member of object com.twitter.finagle.common.zookeeper.ZooKeeperClient
[error] import com.twitter.finagle.common.zookeeper.ZooKeeperClient.ZooKeeperConnectionException;
[error]        ^
[error] .../finagle/finagle-serversets/src/main/java/com/twitter/finagle/common/zookeeper/ServerSetImpl.java:62:8: value ZooKeeperConnectionException is not a member of object com.twitter.finagle.common.zookeeper.ZooKeeperClient
[error] import com.twitter.finagle.common.zookeeper.ZooKeeperClient.ZooKeeperConnectionException;
[error]        ^
model contains 11 documentable templates
[error] .../finagle/finagle-serversets/src/main/java/com/twitter/finagle/common/zookeeper/ZooKeeperUtils.java:31:8: value ZooKeeperConnectionException is not a member of object com.twitter.finagle.common.zookeeper.ZooKeeperClient
[error] import com.twitter.finagle.common.zookeeper.ZooKeeperClient.ZooKeeperConnectionException;
[error]        ^
model contains 28 documentable templates
model contains 16 documentable templates
model contains 22 documentable templates
[warn] .../finagle/finagle-thriftmux/src/main/scala/com/twitter/finagle/thriftmux/MethodBuilder.scala:286:7: The comment for method idempotent contains @inheritdoc, but no parent comment is available to inherit from.
[warn]   def idempotent(maxExtraLoad: Tunable[Double]): MethodBuilder =
[warn]       ^
[warn] .../finagle/finagle-thriftmux/src/main/scala/com/twitter/finagle/thriftmux/MethodBuilder.scala:275:7: The comment for method idempotent contains @inheritdoc, but no parent comment is available to inherit from.
[warn]   def idempotent(maxExtraLoad: Double): MethodBuilder =
[warn]       ^
model contains 14 documentable templates
model contains 56 documentable templates
model contains 56 documentable templates
model contains 29 documentable templates
model contains 56 documentable templates
[info] No documentation generated with unsuccessful compiler run
[error] three errors found
```

**Comment by joroKr21** [comment]
I did
```
project finagle-serversets
++2.13.0
compile
test
```

Maybe needs a rebase?

**Comment by joroKr21** [comment]
@mosesn I rebased and also tried with `+test` from the root project. It works fine for me. What did you run in sbt?

**Comment by mosesn** [comment]
It seems to only fail on our CI infrastructure.  We think it's because we're importing an inner class in java . . . still looking, will keep you posted.

**Comment by yufangong** [comment]
This is merged in https://github.com/twitter/finagle/commit/ef2fc450d6d2c1f23ce604facac3765e97c327b3, Thanks!
If you are curious about the failure before, the issue is strange and @roanta has to make `ZooKeeperConnectionException` be static.
